policies:
  - name: KerasPolicy
    epochs: 50
    max_history: 6
  - name: MemoizationPolicy
    max_history: 6
  - name: FormPolicy

language: "en"

pipeline:
- name: "nlp_spacy"
- name: "tokenizer_spacy"
- name: "intent_entity_featurizer_regex"
- name: "intent_featurizer_spacy"
- name: "ner_crf"
- name: "ner_synonyms"
- name: "intent_classifier_sklearn"
